services:
  app:
    container_name: barber_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:g8eODPeAoW/KauNo/Wm90XLMj8Y5o7l0DksWmRnhVsw=
      APP_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:4001
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: barber
      DB_USERNAME: root
      DB_PASSWORD: root
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file

  db:
    image: mysql:8.0
    container_name: barber_mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barber
    volumes:
      - barber_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

volumes:
  barber_db_data:
